### ISSUE TITLE
send one operation twice?

### ISSUE THREAD

**Issue by we125182** [2muchcoffeecom/ngx-restangular#81] opened 2017-06-19 03:23 UTC
I am new user on angular4 and ngx-restangular. when I create a rest demo. I occured this problem.
```
// config like this
export function RestangularConfigFactory (RestangularProvider) {
  RestangularProvider.setBaseUrl('http://localhost:4000/');
  RestangularProvider.setDefaultHeaders({
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  });
}

// operation like this
this.restangular.all('data').getList();
```
![image](https://user-images.githubusercontent.com/17947588/27268298-5715d9d6-54e1-11e7-9067-c3b07f5c43ea.png)

**Comment by logvinoleg89** [comment] 2017-06-19 07:38
@we125182 can you share full response for both of them

**Comment by logvinoleg89** [comment] 2017-07-12 15:02
the issue is closed as per no details provided.

**Closed as completed by logvinoleg89** 2017-07-12 15:02 UTC
